stages:
  data_ingestion:
    cmd : python src/skinCancerDiagnosis/pipeline/stage_01_dataingestion.py
    deps :
      - src/skinCancerDiagnosis/pipeline/stage_01_dataingestion.py
      - config/config.yaml
    outs :
      - artifacts/data_ingestion/ISIC - 2019
  
  