AUGMENTATION_TYPE : albumentations
# [not, rand_aug, albumentations]
IMAGE_SIZE : [224,224,3]
BATCH_SIZE : 32
INCLUDE_TOP : False
EPOCHS : 100
NUM_CLASSES : 8
CLASS_MODE : categorical
WEIGHTS : imagenet
LEARNING_RATE : 0.001
PATIENCE : 20